export const TopicListen = [
  {
    id: 1,
    title: "Âm nhạc",
    background: require("../img/imgVideo/imgTopic/topic/music.png"),
    content: [
      {
        id: 1,
        image: require("../img/imgVideo/imgTopic/music/music_1.png"),
        name: "Adele - Hello",
        time: "6:07",
        link: "https://www.youtube.com/watch?v=YQHsXMglC9A",
      },
      {
        id: 2,
        image: require("../img/imgVideo/imgTopic/music/music_2.png"),
        name: "Taylor Swift - You Belong With Me",
        time: "3:48",
        link: "https://www.youtube.com/watch?v=VuNIsY6JdUw",
      },
      {
        id: 3,
        image: require("../img/imgVideo/imgTopic/music/music_3.png"),
        name: "ZAYN - Dusk Till Dawn (Official Video) ft. Sia",
        time: "5:38",
        link: "https://www.youtube.com/watch?v=tt2k8PGm-TI",
      },
      {
        id: 4,
        image: require("../img/imgVideo/imgTopic/music/music_4.png"),
        name: "Adele - Rolling in the Deep (Official Music Video)",
        time: "3:54",
        link: "https://www.youtube.com/watch?v=rYEDA3JcQqw",
      },
      {
        id: 5,
        image: require("../img/imgVideo/imgTopic/music/music_5.png"),
        name: "Passenger | Let Her Go (Official Video)",
        time: "4:15",
        link: "https://www.youtube.com/watch?v=RBumgq5yVrA",
      },
      {
        id: 6,
        image: require("../img/imgVideo/imgTopic/music/music_6.png"),
        name: "One Direction - What Makes You Beautiful (Official Video)",
        time: "3:27",
        link: "https://www.youtube.com/watch?v=QJO3ROT-A4E",
      },
      {
        id: 7,
        image: require("../img/imgVideo/imgTopic/music/music_7.png"),
        name: "The Chainsmokers - Closer (Lyric) ft. Halsey",
        time: "4:21",
        link: "https://www.youtube.com/watch?v=PT2_F-1esPk",
      },
    ],
  },

  {
    id: 2,
    title: "Cổ xưa",
    background: require("../img/imgVideo/imgTopic/topic/ancient.png"),
    content: [
      {
        id: 1,
        image: require("../img/imgVideo/imgTopic/ancient/ancient_1.png"),
        name: "The Timeless, Ancient Language of Art | Wangechi Mutu | TED",
        time: "11:26",
        link: "https://www.youtube.com/watch?v=rAhyvSk9cF0",
      },
      {
        id: 2,
        image: require("../img/imgVideo/imgTopic/ancient/ancient_2.png"),
        name: "Are There Deadly Pathogens in Ancient Egyptian Tombs?! | Tut’s Toxic Tomb | Science Channel",
        time: "9:08",
        link: "https://www.youtube.com/watch?v=cllXViWK5-M",
      },
      {
        id: 3,
        image: require("../img/imgVideo/imgTopic/ancient/ancient_3.png"),
        name: "An Inside Look at the Ancient Sumerian City of Nippur | Unearthed | Science Channel",
        time: "3:02",
        link: "https://www.youtube.com/watch?v=V4ptdxaWnks",
      },
      {
        id: 4,
        image: require("../img/imgVideo/imgTopic/ancient/ancient_4.png"),
        name: "Is AI the most important technology of the century?",
        time: "5:19",
        link: "https://www.youtube.com/watch?v=-T__YWoq45I",
      },
      {
        id: 5,
        image: require("../img/imgVideo/imgTopic/ancient/ancient_5.png"),
        name: "How Richest City in History Collapsed",
        time: "21:12",
        link: "https://www.youtube.com/watch?v=c9I9LCvGK2w",
      },
    ],
  },

  {
    id: 3,
    title: "Từ vựng tiếng Anh",
    background: require("../img/imgVideo/imgTopic/topic/vocabulary.png"),
    content: [
      {
        id: 1,
        image: require("../img/imgVideo/imgTopic/vocab/vocab_1.png"),
        name: "Learn English Job Vocabulary and Job Phrases",
        time: "13:17",
        link: "https://www.youtube.com/watch?v=GBiRbb9w3SE",
      },
      {
        id: 2,
        image: require("../img/imgVideo/imgTopic/vocab/vocab_2.png"),
        name: "Learn English Vocabulary for Tourism: resort, cruise, charter, all-inclusive…",
        time: "13:05",
        link: "https://www.youtube.com/watch?v=tWTwb4cTKk0",
      },
      {
        id: 3,
        image: require("../img/imgVideo/imgTopic/vocab/vocab_3.png"),
        name: "Learn English Vocabulary: FAKE NEWS",
        time: "11:50",
        link: "https://www.youtube.com/watch?v=B1XpZbrSEmM",
      },
      {
        id: 4,
        image: require("../img/imgVideo/imgTopic/vocab/vocab_4.png"),
        name: "Learn English vocabulary from French: foie gras, du jour, faux pas...",
        time: "12:30",
        link: "https://www.youtube.com/watch?v=PMoIGPQr7Tw ",
      },
      {
        id: 5,
        image: require("../img/imgVideo/imgTopic/vocab/vocab_5.png"),
        name: "Learn the Top 10 Must-Know Vocabulary for the Restaurant in English",
        time: "4:11",
        link: "https://www.youtube.com/watch?v=9Wrxjge6u6o",
      },
    ],
  },

  {
    id: 4,
    title: "Cafe",
    background: require("../img/imgVideo/imgTopic/topic/cafe.png"),
    content: [
      {
        id: 1,
        image: require("../img/imgVideo/imgTopic/cafe/cafe_1.png"),
        name: "The global coffee crisis is coming",
        time: "11:33",
        link: "https://www.youtube.com/watch?v=6IN4ZcZAUbA",
      },
      {
        id: 2,
        image: require("../img/imgVideo/imgTopic/cafe/cafe_2.png"),
        name: "What Happens To Your Body When You Drink Too Much Coffee",
        time: "3:41",
        link: "https://www.youtube.com/watch?v=1_6_6TAuoGc",
      },
      {
        id: 3,
        image: require("../img/imgVideo/imgTopic/cafe/cafe_3.png"),
        name: "When a barrel of oil was cheaper than your coffee | CNBC Explains",
        time: "6:30",
        link: "https://www.youtube.com/watch?v=y1IDh2-0pyI",
      },
      {
        id: 4,
        image: require("../img/imgVideo/imgTopic/cafe/cafe_4.png"),
        name: "Why Does World's Most Expensive Coffee Come From Poop",
        time: "10:52",
        link: "https://www.youtube.com/watch?v=4vLktLoj-0M",
      },
    ],
  },

  {
    id: 5,
    title: "Đại dương",
    background: require("../img/imgVideo/imgTopic/topic/ocean.png"),
    content: [
      {
        id: 1,
        image: require("../img/imgVideo/imgTopic/ocean/ocean_1.png"),
        name: "Singapore Has This Genius Way of Fixing Ocean Problems",
        time: "9:01",
        link: "https://www.youtube.com/watch?v=bLe13KLGPpg",
      },
      {
        id: 2,
        image: require("../img/imgVideo/imgTopic/ocean/ocean_2.png"),
        name: "When Thousands of Rubber Ducks Were Accidentally Dumped into the Ocean",
        time: "0:49",
        link: "https://www.youtube.com/watch?v=_uuMpVf2R8E",
      },
      {
        id: 3,
        image: require("../img/imgVideo/imgTopic/ocean/ocean_3.png"),
        name: "Đâu Là Nơi Một Đại Dương Kết Thúc Và Bắt Đầu Một Đại Dương Khác?",
        time: "3:56",
        link: "https://www.youtube.com/watch?v=8jPSdDSNSno",
      },
      {
        id: 4,
        image: require("../img/imgVideo/imgTopic/ocean/ocean_4.png"),
        name: "Why The Ocean Needs Salt",
        time: "2:46",
        link: "https://www.youtube.com/watch?v=Gj0LqmNsrCc",
      },
      {
        id: 5,
        image: require("../img/imgVideo/imgTopic/ocean/ocean_5.png"),
        name: "Why the Oceans Are Getting Darker",
        time: "5:49",
        link: "https://www.youtube.com/watch?v=hgL-LiGG2XI",
      },
    ],
  },

  {
    id: 6,
    title: "Việt nam",
    background: require("../img/imgVideo/imgTopic/topic/vietnam.png"),
    content: [
      {
        id: 1,
        image: require("../img/imgVideo/imgTopic/vietnam/vietnam_1.png"),
        name: "Single Woman Picks A Date Based On Their Vietnamese Cooking • Plate To Date",
        time: "10:02",
        link: "https://www.youtube.com/watch?v=icUA4eLL76c",
      },
      {
        id: 2,
        image: require("../img/imgVideo/imgTopic/vietnam/vietnam_2.png"),
        name: "Vietnam had zero coronavirus deaths in 2020. Here’s why. | CNBC Reports",
        time: "7:40",
        link: "https://www.youtube.com/watch?v=LDk9CW82puo",
      },
      {
        id: 3,
        image: require("../img/imgVideo/imgTopic/vietnam/vietnam_3.png"),
        name: "Why Life For USA Tank Crews in Vietnam SUCKED",
        time: "17:30",
        link: "https://www.youtube.com/watch?v=2jK5EV2_cMk",
      },
      {
        id: 4,
        image: require("../img/imgVideo/imgTopic/vietnam/vietnam_4.png"),
        name: "Most Insane Booby Traps Used During the Vietnam War",
        time: "19:25",
        link: "https://www.youtube.com/watch?v=vrBYCNfeUog",
      },
    ],
  },

  {
    id: 7,
    title: "Du lịch",
    background: require("../img/imgVideo/imgTopic/topic/travel.png"),
    content: [
      {
        id: 1,
        image: require("../img/imgVideo/imgTopic/travel/travel_1.png"),
        name: "People Who Have Traveled to a Past Life",
        time: "10:43",
        link: "https://www.youtube.com/watch?v=2gsvqTDpVz4",
      },
      {
        id: 2,
        image: require("../img/imgVideo/imgTopic/travel/travel_2.png"),
        name: "Scientists Reveal How Time Travel Is Actually Possible",
        time: "8:53",
        link: "https://www.youtube.com/watch?v=xjQDKGxPjak",
      },
      {
        id: 3,
        image: require("../img/imgVideo/imgTopic/travel/travel_3.png"),
        name: "The future of space travel is starting right now",
        time: "4:25",
        link: "https://bigthink.com/hard-science/future-of-space-travel/",
      },
      {
        id: 4,
        image: require("../img/imgVideo/imgTopic/travel/travel_4.png"),
        name: "What It's Like To Travel During The Coronavirus Outbreak",
        time: "4:19",
        link: "https://www.youtube.com/watch?v=7AmhOWLnCEI",
      },
      {
        id: 5,
        image: require("../img/imgVideo/imgTopic/travel/travel_5.png"),
        name: "This travel enthusiast skipped a corporate job, but still makes six figures | CNBC Make It",
        time: "6:33",
        link: "https://www.youtube.com/watch?v=-WhJmvSxM_U",
      },
    ],
  },

  {
    id: 8,
    title: "Năng lượng",
    background: require("../img/imgVideo/imgTopic/topic/energy.png"),
    content: [
      {
        id: 1,
        image: require("../img/imgVideo/imgTopic/energy/energy_1.png"),
        name: "The Best Worst Energy Source",
        time: "2:51",
        link: "https://www.youtube.com/watch?v=edBJ1LkvdQQ",
      },
      {
        id: 2,
        image: require("../img/imgVideo/imgTopic/energy/energy_2.png"),
        name: "The Engineering Challenges of Renewable Energy: Crash Course Engineering #30",
        time: "11:31",
        link: "https://www.youtube.com/watch?v=4k5gyYAAEEU",
      },
      {
        id: 3,
        image: require("../img/imgVideo/imgTopic/energy/energy_3.png"),
        name: "The Essentials of Energy",
        time: "5:21",
        link: "https://www.youtube.com/watch?v=ytwIzy3XuGg",
      },
      {
        id: 4,
        image: require("../img/imgVideo/imgTopic/energy/energy_4.png"),
        name: "Who is leading in renewable energy? | CNBC Explains",
        time: "7:19",
        link: "https://www.youtube.com/watch?v=fyqDC_AKVgE",
      },
      {
        id: 5,
        image: require("../img/imgVideo/imgTopic/energy/energy_5.png"),
        name: "Why bitcoin uses so much energy | CNBC Explains",
        time: "8:57",
        link: "https://www.youtube.com/watch?v=JT22_dUsl5M",
      },
      {
        id: 6,
        image: require("../img/imgVideo/imgTopic/energy/energy_6.png"),
        name: "Why the US isn't ready for clean energy",
        time: "6:50",
        link: "https://www.youtube.com/watch?v=s3ScJ_FwaZk",
      },
    ],
  },

  {
    id: 9,
    title: "Thực phẩm",
    background: require("../img/imgVideo/imgTopic/topic/food.png"),
    content: [
      {
        id: 1,
        image: require("../img/imgVideo/imgTopic/food/food_1.png"),
        name: "The Surprising Reason We Eat Spicy Food",
        time: "6:43",
        link: "https://www.youtube.com/watch?app=desktop&v=2sziIUZgdgk",
      },
      {
        id: 2,
        image: require("../img/imgVideo/imgTopic/food/food_2.png"),
        name: "Why beef is the worst food for the climate",
        time: "4:37",
        link: "https://www.youtube.com/watch?v=3lrJYTsKdUM",
      },
      {
        id: 3,
        image: require("../img/imgVideo/imgTopic/food/food_3.png"),
        name: "Trying Japanese and Jewish Fusion Food",
        time: "3:10",
        link: "https://www.youtube.com/watch?v=unWl7dhbXVM",
      },
      {
        id: 4,
        image: require("../img/imgVideo/imgTopic/food/food_4.png"),
        name: "What Really Goes Into Storing Food for the Winter?",
        time: "5:19",
        link: "https://www.youtube.com/watch?v=J0Vi1XDl9aU",
      },
      {
        id: 5,
        image: require("../img/imgVideo/imgTopic/food/food_5.png"),
        name: "What If Bees Went EXTINCT? | Earth Unplugged",
        time: "5:44",
        link: "https://www.youtube.com/watch?v=izGQketQzTc",
      },
      {
        id: 6,
        image: require("../img/imgVideo/imgTopic/food/food_6.png"),
        name: "Which Seafood Is Better for the Environment: Farmed or Wild Caught?",
        time: "10:02",
        link: "https://www.youtube.com/watch?v=zn6AD3khu1U",
      },
    ],
  },

  {
    id: 10,
    title: "Ngôn ngữ",
    background: require("../img/imgVideo/imgTopic/topic/language.png"),
    content: [
      {
        id: 1,
        image: require("../img/imgVideo/imgTopic/language/language_1.png"),
        name: "Language Change and Historical Linguistics: Crash Course Linguistics #13",
        time: "12:12",
        link: "https://www.youtube.com/watch?v=dNkMC92kFLA",
      },
      {
        id: 2,
        image: require("../img/imgVideo/imgTopic/language/language_2.png"),
        name: "Language Shouldn't Be a Barrier to Climate Action | Sophia Kianni | TED Countdown",
        time: "6:50",
        link: "https://www.youtube.com/watch?v=LvNWW_thRC4",
      },
      {
        id: 3,
        image: require("../img/imgVideo/imgTopic/language/language_3.png"),
        name: "Natural Language Processing: Crash Course AI #7",
        time: "13:28",
        link: "https://www.youtube.com/watch?v=oi0JXuL19TA",
      },
      {
        id: 4,
        image: require("../img/imgVideo/imgTopic/language/language_4.png"),
        name: "Kalika Bali: The giant leaps in language technology -- and who's left behind | TED",
        time: "16:25",
        link: "https://www.youtube.com/watch?v=Mkelhs_OVMc",
      },
      {
        id: 5,
        image: require("../img/imgVideo/imgTopic/language/language_5.png"),
        name: "The race to decode a mysterious language - Susan Lupack",
        time: "4:44",
        link: "https://www.youtube.com/watch?v=iePEw_cHp8s",
      },
    ],
  },
];
