export const OxfordChannel = [
  {
    id: 1,
    image: require("../img/imgVideo/imgChannel/oxford/oxford_1.png"),
    text: "20 Office Expressions to Describe Your Workplace - Visual Vocabulary",
    link: "https://www.youtube.com/watch?v=_B2OYMuaXD4&t=1s",
  },
  {
    id: 2,
    image: require("../img/imgVideo/imgChannel/oxford/oxford_2.png"),
    text: "Talking About Online Shopping - Spoken English Lesson",
    link: "https://www.youtube.com/watch?v=eKbdUv4nj_8",
  },
  {
    id: 3,
    image: require("../img/imgVideo/imgChannel/oxford/oxford_3.png"),
    text: "Articles in English - 5 Levels of Difficulty",
    link: "https://www.youtube.com/watch?v=4ZufR8iYL7w&t=6s",
  },
  {
    id: 4,
    image: require("../img/imgVideo/imgChannel/oxford/oxford_4.png"),
    text: "Disagree in English Conversation - Level Up Your English",
    link: "https://www.youtube.com/watch?v=dJ4kPGdUShQ",
  },
  {
    id: 5,
    image: require("../img/imgVideo/imgChannel/oxford/oxford_5.png"),
    text: "English for Working In a Team - Business English Conversation Lesson",
    link: "https://www.youtube.com/watch?v=jTkYnT22G84",
  },
  {
    id: 6,
    image: require("../img/imgVideo/imgChannel/oxford/oxford_6.png"),
    text: "Saying Sorry In English - Level Up Your English Conversation",
    link: "https://www.youtube.com/watch?v=JZjuW6Fjjzg",
  },
  {
    id: 7,
    image: require("../img/imgVideo/imgChannel/oxford/oxford_7.png"),
    text: "How to be Confident and Natural in English Conversation - Taking Turns",
    link: "https://www.youtube.com/watch?v=peNAVhITEZY",
  },
  {
    id: 8,
    image: require("../img/imgVideo/imgChannel/oxford/oxford_8.png"),
    text: "How to Use the Present Perfect Simple and Present Perfect Continuous",
    link: "https://www.youtube.com/watch?v=YwY1SvH3Mp8",
  },
  {
    id: 9,
    image: require("../img/imgVideo/imgChannel/oxford/oxford_9.png"),
    text: "Which English Dictionary is Best for You? - We Reviewed 9 Popular Online Dictionaries",
    link: "https://www.youtube.com/watch?v=d7mc1_7E3gY",
  },
  {
    id: 10,
    image: require("../img/imgVideo/imgChannel/oxford/oxford_10.png"),
    text: "Top 10 Tips for Your IELTS Speaking Exam - Advice from IELTS Examiners & Students",
    link: "https://www.youtube.com/watch?v=EIxTWH-HMRk",
  },
];

export const EngVidChannel = [
  {
    id: 1,
    image: require("../img/imgVideo/imgChannel/engVid/engVid_1.png"),
    text: "12 Confusing English Nouns",
    link: "https://www.youtube.com/watch?v=Cy1mv5OVNZU",
  },
  {
    id: 2,
    image: require("../img/imgVideo/imgChannel/engVid/engVid_2.png"),
    text: "English for Parents: Speak with Your Child’s Teacher | Vocabulary, Questions, Tips",
    link: "https://www.youtube.com/watch?v=hyFgo_xAHhc",
  },
  {
    id: 3,
    image: require("../img/imgVideo/imgChannel/engVid/engVid_3.png"),
    text: "Confusing Subject & Object Pronouns: HE or HIM? I or ME? SHE AND I or HER AND I...?",
    link: "https://www.youtube.com/watch?v=boxixZkx0WU",
  },
  {
    id: 4,
    image: require("../img/imgVideo/imgChannel/engVid/engVid_4.png"),
    text: "“I” or “ME”?",
    link: "https://www.youtube.com/watch?v=zVWoLoxcqqM",
  },
  {
    id: 5,
    image: require("../img/imgVideo/imgChannel/engVid/engVid_5.png"),
    text: "How to use the PAST PERFECT TENSE...today!",
    link: "https://www.youtube.com/watch?v=AFVVvIsRJkA",
  },
  {
    id: 6,
    image: require("../img/imgVideo/imgChannel/engVid/engVid_6.png"),
    text: "English Vocabulary Hack: 15 words, 30 meanings!",
    link: "https://www.youtube.com/watch?v=RjFCl7Mvofo&t=1s",
  },
  {
    id: 7,
    image: require("../img/imgVideo/imgChannel/engVid/engVid_7.png"),
    text: "9 Easy 2-Word English Expressions: “on call”, “on edge”, “on board”...",
    link: "https://www.youtube.com/watch?v=w2MXeT0GYZE",
  },
  {
    id: 8,
    image: require("../img/imgVideo/imgChannel/engVid/engVid_8.png"),
    text: "How to say the days of the week correctly in English",
    link: "https://www.youtube.com/watch?v=xo7J0O3ezrk",
  },
  {
    id: 9,
    image: require("../img/imgVideo/imgChannel/engVid/engVid_9.png"),
    text: "Upgrade Your Vocabulary: 6 ADVANCED ENGLISH VERBS",
    link: "https://www.youtube.com/watch?v=kDDysMNeMyc",
  },
  {
    id: 10,
    image: require("../img/imgVideo/imgChannel/engVid/engVid_10.png"),
    text: "How to Write a Formal Email: 12 Rules",
    link: "https://www.youtube.com/watch?v=Gnnta2gkm_Q",
  },
];

export const EnglishWithLucyChannel = [
  {
    id: 3,
    image: require("../img/imgVideo/imgChannel/lucy/lucy_1.png"),
    text: `How to use "BE SUPPOSED TO" *properly* in English! - Formation, Pronunciation and Usage!`,
    link: "https://www.youtube.com/watch?v=pEa29SOZNkk&t=2s",
  },
  {
    id: 2,
    image: require("../img/imgVideo/imgChannel/lucy/lucy_2.png"),
    text: "C1 (Advanced) Vocabulary in 1 Hour - Ultimate C1 Guide (+ 2 FREE C1 ebooks!)",
    link: "https://www.youtube.com/watch?v=uomydS9kJLQ",
  },
  {
    id: 3,
    image: require("../img/imgVideo/imgChannel/lucy/lucy_3.png"),
    text: "The 5 Business English Mistakes to AVOID! (Seriously!)",
    link: "https://www.youtube.com/watch?v=hmhKtWZor7k",
  },
  {
    id: 4,
    image: require("../img/imgVideo/imgChannel/lucy/lucy_4.png"),
    text: "How to read ALL NUMBERS in English - BIG NUMBERS, Decimals, Dates, Fractions, Phones, Ordinals",
    link: "https://www.youtube.com/watch?v=VYeBYn970a8",
  },
  {
    id: 5,
    image: require("../img/imgVideo/imgChannel/lucy/lucy_5.png"),
    text: "100 Body Part Words in English with Pictures: Advanced Vocabulary Lesson",
    link: "https://www.youtube.com/watch?v=gNAo43v7QYs",
  },
  {
    id: 6,
    image: require("../img/imgVideo/imgChannel/lucy/lucy_6.png"),
    text: "C1-level Grammar and Vocabulary in 1 Hour! (Advanced Level English)",
    link: "https://www.youtube.com/watch?v=2cC3Ke5z6sU",
  },
  {
    id: 7,
    image: require("../img/imgVideo/imgChannel/lucy/lucy_7.png"),
    text: "If you know these 15 Words, your English is EXCELLENT!",
    link: "https://www.youtube.com/watch?v=gXbz6e--R_A",
  },
  {
    id: 8,
    image: require("../img/imgVideo/imgChannel/lucy/lucy_8.png"),
    text: "If you follow THIS 4-part training, you will speak CLEARLY!",
    link: "https://www.youtube.com/watch?v=YabduvXKGdw",
  },
  {
    id: 9,
    image: require("../img/imgVideo/imgChannel/lucy/lucy_9.png"),
    text: "Difference between MADE OF / MADE FROM / MADE WITH / MADE OUT OF - Incredibly Useful English Grammar",
    link: "https://www.youtube.com/watch?v=_Ff59hghTzM",
  },
  {
    id: 10,
    image: require("../img/imgVideo/imgChannel/lucy/lucy_10.png"),
    text: "British Humour Explained (with examples)",
    link: "https://www.youtube.com/watch?v=vkL78BxZ50I",
  },
];

export const VanessaChannel = [
  {
    id: 4,
    image: require("../img/imgVideo/imgChannel/vanessa/vanessa_1.png"),
    text: "Speak With Me About Sleep: English Speaking Practice",
    link: "https://www.youtube.com/watch?v=85sEtpaAKOw",
  },
  {
    id: 2,
    image: require("../img/imgVideo/imgChannel/vanessa/vanessa_2.png"),
    text: "Speak English in 30 Minutes: Advanced English Lesson",
    link: "https://www.youtube.com/watch?v=Iv4F-YV0TxY",
  },
  {
    id: 3,
    image: require("../img/imgVideo/imgChannel/vanessa/vanessa_3.png"),
    text: "Boost your English in 60 days!",
    link: "https://www.youtube.com/watch?v=e6Ezbcqdx3w",
  },
  {
    id: 4,
    image: require("../img/imgVideo/imgChannel/vanessa/vanessa_4.png"),
    text: "THINK and SPEAK in English",
    link: "https://www.youtube.com/watch?v=hWyJ4JXWJEs",
  },
  {
    id: 5,
    image: require("../img/imgVideo/imgChannel/vanessa/vanessa_5.png"),
    text: "Express Yourself in English: Advanced Vocabulary Lesson",
    link: "https://www.youtube.com/watch?v=6eldfa6zjt4",
  },
  {
    id: 6,
    image: require("../img/imgVideo/imgChannel/vanessa/vanessa_6.png"),
    text: "English Conversation Lesson: Work, Jobs, and Daily Life",
    link: "https://www.youtube.com/watch?v=oh0oj-kjgMI",
  },
  {
    id: 7,
    image: require("../img/imgVideo/imgChannel/vanessa/vanessa_7.png"),
    text: "How to Speak Fluent English",
    link: "https://www.youtube.com/watch?v=H6C25LBRVnE",
  },
  {
    id: 8,
    image: require("../img/imgVideo/imgChannel/vanessa/vanessa_8.png"),
    text: "Speak With Me: 2 Hour English Speaking Practice",
    link: "https://www.youtube.com/watch?v=JsgT87TK4So",
  },
  {
    id: 9,
    image: require("../img/imgVideo/imgChannel/vanessa/vanessa_9.png"),
    text: "Daily Life Vocabulary: Around Town [Advanced English Lesson]",
    link: "https://www.youtube.com/watch?v=X4NQUbb_zUE",
  },
  {
    id: 10,
    image: require("../img/imgVideo/imgChannel/vanessa/vanessa_10.png"),
    text: "Daily Life English: Around Town [Advanced Vocabulary Lesson]",
    link: "https://www.youtube.com/watch?v=gOvFsiCUcJE",
  },
];

export const TedEdChannel = [
  {
    id: 5,
    image: require("../img/imgVideo/imgChannel/ted-ed/ted_1.png"),
    text: "Why is the Milky Way flat? - Scott Hershberger",
    link: "https://www.youtube.com/watch?v=phn0bXbcZYY",
  },
  {
    id: 2,
    image: require("../img/imgVideo/imgChannel/ted-ed/ted_2.png"),
    text: "What’s the best way to treat the common cold?",
    link: "https://www.youtube.com/watch?v=oQWmagZmogQ",
  },
  {
    id: 3,
    image: require("../img/imgVideo/imgChannel/ted-ed/ted_3.png"),
    text: "The deadliest thing in your kitchen - George Zaidan",
    link: "https://www.youtube.com/watch?v=NKgXBjkKI_E",
  },
  {
    id: 4,
    image: require("../img/imgVideo/imgChannel/ted-ed/ted_4.png"),
    text: "How do animals regrow their limbs? And why can't humans do it? - Jessica Whited",
    link: "https://www.youtube.com/watch?v=3uTmcG7CgdI",
  },
  {
    id: 5,
    image: require("../img/imgVideo/imgChannel/ted-ed/ted_5.png"),
    text: "What does appendix pain feel like? - David R. Flum",
    link: "https://www.youtube.com/watch?v=8CUEPNcGtWs",
  },
  {
    id: 6,
    image: require("../img/imgVideo/imgChannel/ted-ed/ted_6.png"),
    text: "The surprising reason zebras have stripes - Cella Wright",
    link: "https://www.youtube.com/watch?v=QJB0nmEjbDY",
  },
  {
    id: 7,
    image: require("../img/imgVideo/imgChannel/ted-ed/ted_7.png"),
    text: "The surprising effects of outer space on the human body - Tejal Gala",
    link: "https://www.youtube.com/watch?v=uuc6bXxgvh8",
  },
  {
    id: 8,
    image: require("../img/imgVideo/imgChannel/ted-ed/ted_8.png"),
    text: "The tale of the boy who tricked a tyrant - Paschal Kyiiripuo Kyoore",
    link: "https://www.youtube.com/watch?v=vtjHHnu_IB0",
  },
  {
    id: 9,
    image: require("../img/imgVideo/imgChannel/ted-ed/ted_9.png"),
    text: "The tragedy of the one guy who was right about the Trojan Horse - Noah Charney",
    link: "https://www.youtube.com/watch?v=_ZmTQIFA9fY",
  },
  {
    id: 10,
    image: require("../img/imgVideo/imgChannel/ted-ed/ted_10.png"),
    text: "Is this the most valuable thing in the ocean? - David Biello",
    link: "https://www.youtube.com/watch?v=V8Bn0UPpGCw",
  },
];

export const topicVideo = [
  {
    id: 1,
    title: "Âm nhạc",
    background: require("../img/imgVideo/imgTopic/topic/music.png"),
    content: [
      {
        id: 1,
        image: require("../img/imgVideo/imgTopic/music/music_1.png"),
        name: "Adele - Hello",
        time: "6:07",
        link: "https://www.youtube.com/watch?v=YQHsXMglC9A",
      },
      {
        id: 2,
        image: require("../img/imgVideo/imgTopic/music/music_2.png"),
        name: "Taylor Swift - You Belong With Me",
        time: "3:48",
        link: "https://www.youtube.com/watch?v=VuNIsY6JdUw",
      },
      {
        id: 3,
        image: require("../img/imgVideo/imgTopic/music/music_3.png"),
        name: "ZAYN - Dusk Till Dawn (Official Video) ft. Sia",
        time: "5:38",
        link: "https://www.youtube.com/watch?v=tt2k8PGm-TI",
      },
      {
        id: 4,
        image: require("../img/imgVideo/imgTopic/music/music_4.png"),
        name: "Adele - Rolling in the Deep (Official Music Video)",
        time: "3:54",
        link: "https://www.youtube.com/watch?v=rYEDA3JcQqw",
      },
      {
        id: 5,
        image: require("../img/imgVideo/imgTopic/music/music_5.png"),
        name: "Passenger | Let Her Go (Official Video)",
        time: "4:15",
        link: "https://www.youtube.com/watch?v=RBumgq5yVrA",
      },
      {
        id: 6,
        image: require("../img/imgVideo/imgTopic/music/music_6.png"),
        name: "One Direction - What Makes You Beautiful (Official Video)",
        time: "3:27",
        link: "https://www.youtube.com/watch?v=QJO3ROT-A4E",
      },
      {
        id: 7,
        image: require("../img/imgVideo/imgTopic/music/music_7.png"),
        name: "The Chainsmokers - Closer (Lyric) ft. Halsey",
        time: "4:21",
        link: "https://www.youtube.com/watch?v=PT2_F-1esPk",
      },
    ],
  },

  {
    id: 2,
    title: "Cổ xưa",
    background: require("../img/imgVideo/imgTopic/topic/ancient.png"),
    content: [
      {
        id: 1,
        image: require("../img/imgVideo/imgTopic/ancient/ancient_1.png"),
        name: "The Timeless, Ancient Language of Art | Wangechi Mutu | TED",
        time: "11:26",
        link: "https://www.youtube.com/watch?v=rAhyvSk9cF0",
      },
      {
        id: 2,
        image: require("../img/imgVideo/imgTopic/ancient/ancient_2.png"),
        name: "Are There Deadly Pathogens in Ancient Egyptian Tombs?! | Tut’s Toxic Tomb | Science Channel",
        time: "9:08",
        link: "https://www.youtube.com/watch?v=cllXViWK5-M",
      },
      {
        id: 3,
        image: require("../img/imgVideo/imgTopic/ancient/ancient_3.png"),
        name: "An Inside Look at the Ancient Sumerian City of Nippur | Unearthed | Science Channel",
        time: "3:02",
        link: "https://www.youtube.com/watch?v=V4ptdxaWnks",
      },
      {
        id: 4,
        image: require("../img/imgVideo/imgTopic/ancient/ancient_4.png"),
        name: "Is AI the most important technology of the century?",
        time: "5:19",
        link: "https://www.youtube.com/watch?v=-T__YWoq45I",
      },
      {
        id: 5,
        image: require("../img/imgVideo/imgTopic/ancient/ancient_5.png"),
        name: "How Richest City in History Collapsed",
        time: "21:12",
        link: "https://www.youtube.com/watch?v=c9I9LCvGK2w",
      },
    ],
  },

  {
    id: 3,
    title: "Từ vựng tiếng Anh",
    background: require("../img/imgVideo/imgTopic/topic/vocabulary.png"),
    content: [
      {
        id: 1,
        image: require("../img/imgVideo/imgTopic/vocab/vocab_1.png"),
        name: "Learn English Job Vocabulary and Job Phrases",
        time: "13:17",
        link: "https://www.youtube.com/watch?v=GBiRbb9w3SE",
      },
      {
        id: 2,
        image: require("../img/imgVideo/imgTopic/vocab/vocab_2.png"),
        name: "Learn English Vocabulary for Tourism: resort, cruise, charter, all-inclusive…",
        time: "13:05",
        link: "https://www.youtube.com/watch?v=tWTwb4cTKk0",
      },
      {
        id: 3,
        image: require("../img/imgVideo/imgTopic/vocab/vocab_3.png"),
        name: "Learn English Vocabulary: FAKE NEWS",
        time: "11:50",
        link: "https://www.youtube.com/watch?v=B1XpZbrSEmM",
      },
      {
        id: 4,
        image: require("../img/imgVideo/imgTopic/vocab/vocab_4.png"),
        name: "Learn English vocabulary from French: foie gras, du jour, faux pas...",
        time: "12:30",
        link: "https://www.youtube.com/watch?v=PMoIGPQr7Tw ",
      },
      {
        id: 5,
        image: require("../img/imgVideo/imgTopic/vocab/vocab_5.png"),
        name: "Learn the Top 10 Must-Know Vocabulary for the Restaurant in English",
        time: "4:11",
        link: "https://www.youtube.com/watch?v=9Wrxjge6u6o",
      },
    ],
  },

  {
    id: 4,
    title: "Cafe",
    background: require("../img/imgVideo/imgTopic/topic/cafe.png"),
    content: [
      {
        id: 1,
        image: require("../img/imgVideo/imgTopic/cafe/cafe_1.png"),
        name: "The global coffee crisis is coming",
        time: "11:33",
        link: "https://www.youtube.com/watch?v=6IN4ZcZAUbA",
      },
      {
        id: 2,
        image: require("../img/imgVideo/imgTopic/cafe/cafe_2.png"),
        name: "What Happens To Your Body When You Drink Too Much Coffee",
        time: "3:41",
        link: "https://www.youtube.com/watch?v=1_6_6TAuoGc",
      },
      {
        id: 3,
        image: require("../img/imgVideo/imgTopic/cafe/cafe_3.png"),
        name: "When a barrel of oil was cheaper than your coffee | CNBC Explains",
        time: "6:30",
        link: "https://www.youtube.com/watch?v=y1IDh2-0pyI",
      },
      {
        id: 4,
        image: require("../img/imgVideo/imgTopic/cafe/cafe_4.png"),
        name: "Why Does World's Most Expensive Coffee Come From Poop",
        time: "10:52",
        link: "https://www.youtube.com/watch?v=4vLktLoj-0M",
      },
    ],
  },

  {
    id: 5,
    title: "Đại dương",
    background: require("../img/imgVideo/imgTopic/topic/ocean.png"),
    content: [
      {
        id: 1,
        image: require("../img/imgVideo/imgTopic/ocean/ocean_1.png"),
        name: "Singapore Has This Genius Way of Fixing Ocean Problems",
        time: "9:01",
        link: "https://www.youtube.com/watch?v=bLe13KLGPpg",
      },
      {
        id: 2,
        image: require("../img/imgVideo/imgTopic/ocean/ocean_2.png"),
        name: "When Thousands of Rubber Ducks Were Accidentally Dumped into the Ocean",
        time: "0:49",
        link: "https://www.youtube.com/watch?v=_uuMpVf2R8E",
      },
      {
        id: 3,
        image: require("../img/imgVideo/imgTopic/ocean/ocean_3.png"),
        name: "Đâu Là Nơi Một Đại Dương Kết Thúc Và Bắt Đầu Một Đại Dương Khác?",
        time: "3:56",
        link: "https://www.youtube.com/watch?v=8jPSdDSNSno",
      },
      {
        id: 4,
        image: require("../img/imgVideo/imgTopic/ocean/ocean_4.png"),
        name: "Why The Ocean Needs Salt",
        time: "2:46",
        link: "https://www.youtube.com/watch?v=Gj0LqmNsrCc",
      },
      {
        id: 5,
        image: require("../img/imgVideo/imgTopic/ocean/ocean_5.png"),
        name: "Why the Oceans Are Getting Darker",
        time: "5:49",
        link: "https://www.youtube.com/watch?v=hgL-LiGG2XI",
      },
    ],
  },

  {
    id: 6,
    title: "Việt nam",
    background: require("../img/imgVideo/imgTopic/topic/vietnam.png"),
    content: [
      {
        id: 1,
        image: require("../img/imgVideo/imgTopic/vietnam/vietnam_1.png"),
        name: "Single Woman Picks A Date Based On Their Vietnamese Cooking • Plate To Date",
        time: "10:02",
        link: "https://www.youtube.com/watch?v=icUA4eLL76c",
      },
      {
        id: 2,
        image: require("../img/imgVideo/imgTopic/vietnam/vietnam_2.png"),
        name: "Vietnam had zero coronavirus deaths in 2020. Here’s why. | CNBC Reports",
        time: "7:40",
        link: "https://www.youtube.com/watch?v=LDk9CW82puo",
      },
      {
        id: 3,
        image: require("../img/imgVideo/imgTopic/vietnam/vietnam_3.png"),
        name: "Why Life For USA Tank Crews in Vietnam SUCKED",
        time: "17:30",
        link: "https://www.youtube.com/watch?v=2jK5EV2_cMk",
      },
      {
        id: 4,
        image: require("../img/imgVideo/imgTopic/vietnam/vietnam_4.png"),
        name: "Most Insane Booby Traps Used During the Vietnam War",
        time: "19:25",
        link: "https://www.youtube.com/watch?v=vrBYCNfeUog",
      },
    ],
  },

  {
    id: 7,
    title: "Du lịch",
    background: require("../img/imgVideo/imgTopic/topic/travel.png"),
    content: [
      {
        id: 1,
        image: require("../img/imgVideo/imgTopic/travel/travel_1.png"),
        name: "People Who Have Traveled to a Past Life",
        time: "10:43",
        link: "https://www.youtube.com/watch?v=2gsvqTDpVz4",
      },
      {
        id: 2,
        image: require("../img/imgVideo/imgTopic/travel/travel_2.png"),
        name: "Scientists Reveal How Time Travel Is Actually Possible",
        time: "8:53",
        link: "https://www.youtube.com/watch?v=xjQDKGxPjak",
      },
      {
        id: 3,
        image: require("../img/imgVideo/imgTopic/travel/travel_3.png"),
        name: "The future of space travel is starting right now",
        time: "4:25",
        link: "https://bigthink.com/hard-science/future-of-space-travel/",
      },
      {
        id: 4,
        image: require("../img/imgVideo/imgTopic/travel/travel_4.png"),
        name: "What It's Like To Travel During The Coronavirus Outbreak",
        time: "4:19",
        link: "https://www.youtube.com/watch?v=7AmhOWLnCEI",
      },
      {
        id: 5,
        image: require("../img/imgVideo/imgTopic/travel/travel_5.png"),
        name: "This travel enthusiast skipped a corporate job, but still makes six figures | CNBC Make It",
        time: "6:33",
        link: "https://www.youtube.com/watch?v=-WhJmvSxM_U",
      },
    ],
  },

  {
    id: 8,
    title: "Năng lượng",
    background: require("../img/imgVideo/imgTopic/topic/energy.png"),
    content: [
      {
        id: 1,
        image: require("../img/imgVideo/imgTopic/energy/energy_1.png"),
        name: "The Best Worst Energy Source",
        time: "2:51",
        link: "https://www.youtube.com/watch?v=edBJ1LkvdQQ",
      },
      {
        id: 2,
        image: require("../img/imgVideo/imgTopic/energy/energy_2.png"),
        name: "The Engineering Challenges of Renewable Energy: Crash Course Engineering #30",
        time: "11:31",
        link: "https://www.youtube.com/watch?v=4k5gyYAAEEU",
      },
      {
        id: 3,
        image: require("../img/imgVideo/imgTopic/energy/energy_3.png"),
        name: "The Essentials of Energy",
        time: "5:21",
        link: "https://www.youtube.com/watch?v=ytwIzy3XuGg",
      },
      {
        id: 4,
        image: require("../img/imgVideo/imgTopic/energy/energy_4.png"),
        name: "Who is leading in renewable energy? | CNBC Explains",
        time: "7:19",
        link: "https://www.youtube.com/watch?v=fyqDC_AKVgE",
      },
      {
        id: 5,
        image: require("../img/imgVideo/imgTopic/energy/energy_5.png"),
        name: "Why bitcoin uses so much energy | CNBC Explains",
        time: "8:57",
        link: "https://www.youtube.com/watch?v=JT22_dUsl5M",
      },
      {
        id: 6,
        image: require("../img/imgVideo/imgTopic/energy/energy_6.png"),
        name: "Why the US isn't ready for clean energy",
        time: "6:50",
        link: "https://www.youtube.com/watch?v=s3ScJ_FwaZk",
      },
    ],
  },

  {
    id: 9,
    title: "Thực phẩm",
    background: require("../img/imgVideo/imgTopic/topic/food.png"),
    content: [
      {
        id: 1,
        image: require("../img/imgVideo/imgTopic/food/food_1.png"),
        name: "The Surprising Reason We Eat Spicy Food",
        time: "6:43",
        link: "https://www.youtube.com/watch?app=desktop&v=2sziIUZgdgk",
      },
      {
        id: 2,
        image: require("../img/imgVideo/imgTopic/food/food_2.png"),
        name: "Why beef is the worst food for the climate",
        time: "4:37",
        link: "https://www.youtube.com/watch?v=3lrJYTsKdUM",
      },
      {
        id: 3,
        image: require("../img/imgVideo/imgTopic/food/food_3.png"),
        name: "Trying Japanese and Jewish Fusion Food",
        time: "3:10",
        link: "https://www.youtube.com/watch?v=unWl7dhbXVM",
      },
      {
        id: 4,
        image: require("../img/imgVideo/imgTopic/food/food_4.png"),
        name: "What Really Goes Into Storing Food for the Winter?",
        time: "5:19",
        link: "https://www.youtube.com/watch?v=J0Vi1XDl9aU",
      },
      {
        id: 5,
        image: require("../img/imgVideo/imgTopic/food/food_5.png"),
        name: "What If Bees Went EXTINCT? | Earth Unplugged",
        time: "5:44",
        link: "https://www.youtube.com/watch?v=izGQketQzTc",
      },
      {
        id: 6,
        image: require("../img/imgVideo/imgTopic/food/food_6.png"),
        name: "Which Seafood Is Better for the Environment: Farmed or Wild Caught?",
        time: "10:02",
        link: "https://www.youtube.com/watch?v=zn6AD3khu1U",
      },
    ],
  },

  {
    id: 10,
    title: "Ngôn ngữ",
    background: require("../img/imgVideo/imgTopic/topic/language.png"),
    content: [
      {
        id: 1,
        image: require("../img/imgVideo/imgTopic/language/language_1.png"),
        name: "Language Change and Historical Linguistics: Crash Course Linguistics #13",
        time: "12:12",
        link: "https://www.youtube.com/watch?v=dNkMC92kFLA",
      },
      {
        id: 2,
        image: require("../img/imgVideo/imgTopic/language/language_2.png"),
        name: "Language Shouldn't Be a Barrier to Climate Action | Sophia Kianni | TED Countdown",
        time: "6:50",
        link: "https://www.youtube.com/watch?v=LvNWW_thRC4",
      },
      {
        id: 3,
        image: require("../img/imgVideo/imgTopic/language/language_3.png"),
        name: "Natural Language Processing: Crash Course AI #7",
        time: "13:28",
        link: "https://www.youtube.com/watch?v=oi0JXuL19TA",
      },
      {
        id: 4,
        image: require("../img/imgVideo/imgTopic/language/language_4.png"),
        name: "Kalika Bali: The giant leaps in language technology -- and who's left behind | TED",
        time: "16:25",
        link: "https://www.youtube.com/watch?v=Mkelhs_OVMc",
      },
      {
        id: 5,
        image: require("../img/imgVideo/imgTopic/language/language_5.png"),
        name: "The race to decode a mysterious language - Susan Lupack",
        time: "4:44",
        link: "https://www.youtube.com/watch?v=iePEw_cHp8s",
      },
    ],
  },
];
